application:
  # cluster id if not set the server will run as a independent server, and id will be set as independent_Project.key()
  id: jj2
  # cluster name default as the cluster id
  name: jj2
  # internal server ip, other can access, 0.0.0.0
  internalIp: 127.0.0.1
  # print cli log or not
  debug: false
# log config
log:
  # log dir
  dir:
  # max size (M) default:  100
  maxSize: 100
  # max backup  default:  5
  maxBackup: 5
  # max age (day)  default:  5
  maxAge: 5
  # level, default=info,  debug,info, warn,error...
  level: debug
  # trace level, default=error,  debug,info, warn,error...
  traceLevel: error
http:
  Name: jj2
  # Trusted proxy ip, the gateway ip, multi
  trustedProxies:
    - 127.0.0.1
  #enable http engine to debug mode
  routeDebug: false
  # asset dir or root dir
  dir:
  # dir as root, without pkg asset
  dirRoot: false
  # port
  port: 8090
  # Api Host
  apiHost: 127.0.0.1
